### ISSUE TITLE
Implement security checklist

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/WordPress.Demos.Manager#12]
Source: https://www.process.st/server-security/

[Checklist](https://app.process.st/templates/Server-Security-Checklist-jI73hxyrbeu_dsAj_EdE7A/view/tasks/ltak9PWXN5e8GYnzuqtEAw)

- [x] Update your package list and upgrade your OS
- [ ] Remove unnecessary packages
- [x] Detect weak passwords with John the Ripper
- [x] Verify no accounts have empty passwords
- [ ] Set password rules
- [ ] Set password expiration in login.defs
~~- [ ] Disable USB devices (for headless servers)~~ not applicable on a VPS
- [ ] Check which services are started at boot time
- [ ] Detect all world-writable files
- [ ] Configure iptables to block common attacks
- [ ] Set GRUB boot loader password
- [ ] Disable interactive hotkey startup at boot
- [ ] Use Logwatch to monitor suspicious log messages
- [ ] Enable auditd to check for read/write events
- [ ] Secure any Apache servers
- [ ] Install and configure UFW
- [ ] Configure SSH securely
- [ ] Disable telnet
- [ ] Configure sysctl securely
- [ ] Lock user accounts after failed attempts with Fail2Ban
- [ ] Configure root user timeout
- [ ] Check for hidden open ports with netstat
- [ ] Set root permissions for core system files
- [ ] Scan for rootkits

In the long run:

- [ ] Configure snapshot incremental backups with rsnapshot
- [ ] Use apt to get the latest security updates
- [ ] Regularly check the security announcements for your server’s OS
- [ ] Disable FTP, use only SFTP
